### ISSUE TITLE
Javascript error in the console when adding an episode prevents saving

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#292]
This is preventing me from saving. My tags were "asdf asdf" but the error also shows up when adding "foo bar". Below is what I see in the console:

prx.org-frontend-0.0.1.min.fd6850f2.js:2 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.17/ngRepeat/dupes?p0=tag%20in%20story.current.tags&p1=string%3Aa&p2=a
   at Error (native)
   at https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:1:417
   at https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:4:20633
   at Object.fn (https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:2:27455)
   at d.$get.d.$digest (https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:2:28061)
   at d.$get.d.$apply (https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:2:29491)
   at Lo.$$debounceViewValueCommit (https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:4:17270)
   at Lo.$setViewValue (https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:4:16998)
   at HTMLInputElement.l (https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:3:11556)
   at HTMLInputElement.n (https://alpha.prx.org/assets/prx.org-frontend-0.0.1.min.fd6850f2.js:1:13676)
PUT https://cms.prx.org/api/v1/stories/158297 500 (Internal Server Error)

**Comment by chrisrhoden** [comment]
This is actually not what is preventing saving (the 500 error at the end is what is preventing saving) - this is the result of tags being mishandled

in any event, being addressed by #279
